### PR TITLE
1d physics

### PR DESCRIPTION
**Pull request by andytorrestb**
added notional 1d docking approach case.

WIP. convention needs to be changed such that the VV is approaching the docking point from the positive x side.

### CODE REVIEW

**Review by nickpalumbo8 — CHANGES_REQUESTED** [review]
1 - TCD.txt should be renamed to tcf_1d_approach.txt
2 - JFH_1d_approach.A should be renamed to jfh_1d_approach.A and dcms should be reformatted to match heritage
3 - config.ini should be updated accordingly

4 - New methods implemented across all functions should be listed in their respective class description’s method list (such as print_jfh_1d_approach in RPOD.py and print_JFH_param_curve and graph_param_curve in JetFiringHistory.py)
5 - Old methods that are no longer in RPOD.py such as graph_param_curve and print_JFH_param_curve should be removed from the class description’s method list

6 - Changes to rpod_integration_test_01.py required: 
6.1 - m should be 14000
6.2 - h should be 11
6.3 - r should be 1.65
6.4 - Last Changed should be updated

7 - MissionPlanner.py:
	7.1 - calc_dv and calc_delta_mass_v_e have undergone changes in fuel_calc_new. I’d prefer to merge fuel_calc_new first and then rework 1d-physics to use its updated methods if that’s okay

**Comment by nickpalumbo8** [comment]
calc_dv and calc_delta_mass_v_e have undergone changes in fuel_calc_new. I’d prefer to merge fuel_calc_new first and then rework 1d-physics to use its updated methods if that’s okay

**Comment by andytorrestb** [comment]
> calc_dv and calc_delta_mass_v_e have undergone changes in fuel_calc_new. I’d prefer to merge fuel_calc_new first and then rework 1d-physics to use its updated methods if that’s okay

ran changes locally. they work well. standing by to merge fuel-calc first.

**Review by nickpalumbo8 — APPROVED** [review]
Besides importing MissionPlanner unnecessarily in rpod_integration_test_01.py and the thrusters not being in the correct positions in paraview because the tcf was built to work with the ccf on the tcd_decoupling branch, its all good.

I'd really like to merge the tcd_decoupling branch and update these old STLs with the LM and ATV216 thruster CADs for a better visualization.

Next up is getting the cant sweep to work with the updated tcf and STLs and integrating the plume models into the optimizer. I'm hoping to be able to grab the max heat flux for the current and next step, then compare them and if the next step has a lower max heat flux, then increase the cant angle. To get the visualization to work correctly I'm going to need to pass in the current cant angle to the transform function for the STL before it is graphed.

**Pull request merged**
