### PR TITLE
Plume normal fix

### PR DESCRIPTION
**Pull request by nickpalumbo8**
Plume normal changed from z direction to x direction. All stl files reoriented and meshed. All jfhs and tcfs updated accordingly.

### CODE REVIEW

**Comment by andytorrestb** [comment]
please provide professional description of changes.

**Review by pearcepatterson — APPROVED** [review]
good

**Review by JuanPabloRoldan — APPROVED** [review]
love the fast run time

**Comment by andytorrestb** [comment]
1. Restore intermediate STL files for processing. 
2. Stick to heritage formatting with TCF files. Need to match the significant figures provided.

**Review by andytorrestb — APPROVED** [review]

**Pull request merged**
